# Goreleaser config for Go binary release
project_name: nibble
builds:
  - main: ./main.go
    binary: nibble
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - "nibble"
release:
  github:
    owner: saberd
    name: nibble
    draft: false
    prerelease: false
    tag_name: "v{{ .Version }}"
    token: ${{ secrets.GITHUB_TOKEN }}
