version: 2

# Goreleaser config for Go binary release
project_name: nibble
dist: .artifacts/goreleaser
builds:
  - main: .
    binary: nibble
    ldflags:
      - -X main.version={{ .Version }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
release:
  github:
    owner: backendsystems
    name: nibble
  draft: false
  prerelease: false
homebrew_casks:
  - name: nibble
    repository:
      owner: backendsystems
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/backendsystems/nibble"
    description: "Fast local network scanner with hardware identification and a terminal UI"
    license: "MIT"
    commit_author:
      name: "github-actions[bot]"
      email: "github-actions[bot]@users.noreply.github.com"
