version: 2

# Goreleaser config for Go binary release
project_name: nibble
builds:
  - main: ./main.go
    binary: nibble
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - "nibble"
release:
  github:
    owner: saberd
    name: nibble
    draft: false
    prerelease: false
    tag_name: "v{{ .Version }}"
    token: ${{ secrets.GITHUB_TOKEN }}
brews:
  - name: nibble
    repository:
      owner: saberd
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/saberd/nibble"
    description: "Fast local network scanner with hardware identification and a terminal UI"
    license: "MIT"
    commit_author:
      name: "github-actions[bot]"
      email: "github-actions[bot]@users.noreply.github.com"
    test: |
      system "#{bin}/nibble", "--help"
