name: Smoke test nibble startup
description: Verify nibble was installed correctly.
runs:
  using: composite
  steps:
    - name: Smoke test nibble startup
      shell: bash
      run: nibble -version
